// src/pages/Home/components/Form/components/Accomodation/Accomodation.tsx
import { Dispatch, SetStateAction, useEffect, useRef, useState } from 'react';
import { AccommodationType } from '../../../../../../types';
import { AccommodationComponent } from './Accomodation.WC';
import './Accomodation.WC';
import { ACCOMMODATION_CONSTANTS } from './constants';

type ValidType = {
  name: boolean;
  address: boolean;
  type: boolean;
};

type SetterType = Dispatch<SetStateAction<AccommodationType>> | Dispatch<SetStateAction<ValidType>>;

const Accommodation = () => {
  const { IMAGES, REQUIRED_FIELDS, LISTENER_TYPES, EVENT_TYPES } = ACCOMMODATION_CONSTANTS;
  const [isValid, setIsValid] = useState<ValidType>({
    name: true,
    address: true,
    type: true,
  });
  const [data, setData] = useState<AccommodationType>({
    name: '',
    address: '',
    description: '',
    type: 'Villa',
    images: [],
  });

  const componentRef = useRef<AccommodationComponent | null>(null);

  const setState = (
    key: keyof AccommodationType,
    value: string | Array<string> | boolean,
    setter: SetterType
  ) => {
    setter((prev: any) => ({ ...prev, [key]: value }));
  };

  useEffect(() => {
    const component = componentRef.current;
    if (!component) return;

    const setupListener = (key: keyof AccommodationType) => {
      component.addEventListener(LISTENER_TYPES.KEY.replace('key', key), (e: Event) => {
        const eventDetail = (e as CustomEvent).detail;

        if (key === IMAGES) {
          if (!data.images.includes(eventDetail.value)) {
            setState(key, eventDetail.value, setData);
            return;
          }
        }

        if (REQUIRED_FIELDS.includes(key)) {
          setState(key, eventDetail.isValid, setIsValid);
        }

        setState(key, eventDetail.value || '', setData);
      });
    };

    const keys = Object.keys(data) as Array<keyof AccommodationType>;
    keys.forEach(setupListener);

    if (!component.callback)
      component.callback = () =>
        dispatchEvent(
          new CustomEvent(EVENT_TYPES.SUBMIT, {
            detail: data,
            bubbles: true,
            composed: true,
          })
        );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  useEffect(() => {
    const component = componentRef.current;
    if (!component) return;
    const disabled = !Object.values(isValid).every(Boolean);
    component.valid = disabled;
  }, [isValid]);

  return <wc-accommodation ref={componentRef}></wc-accommodation>;
};

export { Accommodation };

// src/pages/Home/components/Form/components/Accomodation/Accomodation.WC.tsx
import { createRoot, Root } from 'react-dom/client';
import { getTwind } from '../../../../../../utils';
import { ImageUploader, Name, Address, Description, Type } from './components/';
import { AccommodationType } from '../../../../../../types';
import './components';

const { sheet, tw } = getTwind();

class AccommodationComponent extends HTMLElement {
  private shadow: ShadowRoot;
  private root: Root;

  private _isValid: Record<string, boolean> = {
    name: false,
    address: false,
    type: true,
  };

  private _accommodationInfo: AccommodationType = {
    name: '',
    address: '',
    description: '',
    type: 'Villa',
    images: [],
  };

  constructor() {
    super();
    this.shadow = this.attachShadow({ mode: 'open' });
    this.shadow.adoptedStyleSheets = [sheet.target];
    this.root = createRoot(this.shadow);
  }

  connectedCallback() {
    this.render();
    this._setupEventListeners();
  }

  private _setupEventListeners() {
    const requiredFields = ['name', 'address', 'description'];
    const setupListener = (key: keyof AccommodationType) => {
      this.shadow.addEventListener(`${key}-info`, (e: Event) => {
        const eventDetail = (e as CustomEvent).detail;

        if (key === 'images') {
          const images = this._accommodationInfo.images;
          if (!images.includes(eventDetail.value)) {
            images.push(eventDetail.value);
            return;
          }
        }

        if (requiredFields.includes(key)) {
          this._isValid[key] = Boolean(eventDetail.isValid);
          this._updateSubmitButtonState();
        }

        this._accommodationInfo[key] = eventDetail.value || '';
      });
    };

    const keys = Object.keys(this._accommodationInfo) as Array<keyof AccommodationType>;
    keys.forEach(setupListener);

    this.shadow.addEventListener('submit', (e: Event) => {
      e.preventDefault();
      this.dispatchEvent(
        new CustomEvent('accommodation-info-submit', {
          detail: this._accommodationInfo,
          bubbles: true,
          composed: true,
        })
      );
    });
  }

  private _updateSubmitButtonState() {
    const button = this.shadow.querySelector('button');
    button!.disabled = !Object.values(this._isValid).every(Boolean);
  }

  private _getName() {
    return <Name />;
  }

  private _getAddress() {
    return <Address />;
  }

  private _getDescription() {
    return <Description />;
  }

  private _getType() {
    return <Type />;
  }

  private _getUploadPhoto() {
    return <ImageUploader />;
  }

  private _getSubmit() {
    return (
      <button
        type="submit"
        className={tw`w-full px-4 py-2 mt-auto mb-[50px] text-white bg-indigo-500 rounded-md hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-30`}
        disabled
      >
        Next
      </button>
    );
  }

  render() {
    const reactNode = (
      <form id="accommodation-form" className={tw`w-full h-full`}>
        <div className={tw`flex flex-col gap-2 w-full h-full p-4`}>
          {this._getName()}
          {this._getAddress()}
          {this._getDescription()}
          {this._getType()}
          {this._getUploadPhoto()}
          {this._getSubmit()}
        </div>
      </form>
    );

    this.root.render(reactNode);
  }
}

customElements.define('wc-accommodation', AccommodationComponent);

export { AccommodationComponent };
